In [19]:
#Milestone 2: Flat file

import pandas as pd

#Importing the CSV file
cars = pd.read_csv('CO2 Emissions_Canada.csv')

#Removing all categorical series besides the make and model. Also removing the fuel consumption (MPG) series as it is redundant. 
cars[['Make', 'Model', 'Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'CO2 Emissions(g/km)']]

#Capitalizing all strings to ensure duplicates can be aggregated
cars['Make'] = cars['Make'].str.upper()
cars['Model'] = cars['Model'].str.upper()

#Removing all hybrid vehicles from the data frame, as they are outliers
cars = cars[~cars['Model'].str.contains('HYBRID')]

#Grouping the cars by make and model then aggregating duplicate models by taking the mean of the values
cars = cars.groupby(['Make', 'Model'], as_index = False).mean()

#Dropping the trim names from the model by splitting the model names and only returning the first word to the series.
#Trim names do not follow any naming convention, and thus, make the data harder to analyze.
A = cars['Model'].str.split(' ')
new_models = []
for item in A:
    #6 car brands have model names with multiple words, so these 6 will have the subsequent words returned as well.
    if item[0] == 'GRAND' or item[0] == 'SANTA' or item[0] == 'NEW' or item[0] == 'FLYING' or item[0] == 'RANGE':
        new_models.append(item[0] + ' ' + item[1])
    elif item[0] == 'TOWN':
        new_models.append(item[0] + ' ' + item[1] + ' ' + item[2])
    else:
        new_models.append(item[0])

#Converting the truncated model names to a Pandas series and adding it as the new 'Model' column in the data frame.
cars['Model'] = pd.Series(new_models)

#Now that the trim names have been dropped, I will aggregate all of the same models to give one trim average for each model.
cars = cars.groupby(['Make', 'Model'], as_index = False).mean()

#Mazda has a bad habit of adding their make name to some of their models. I remove the make name here to avoid confusion.
cars['Model'] = cars['Model'].str.replace('MAZDA2', '2')
cars['Model'] = cars['Model'].str.replace('MAZDA3', '3')
cars['Model'] = cars['Model'].str.replace('MAZDA5', '5')
cars['Model'] = cars['Model'].str.replace('MAZDA6', '6')

#Final result: A data frame of cars cleaned of outliers, where each row represents one unique car model (the average of all its trim levels) and each column is a numerical attribute. 
cars

,Make,Model,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,2.311111,4.000000,9.944444,6.966667,8.600000,32.777778,199.222222
1,ACURA,MDX,3.500000,6.000000,12.404167,9.175000,10.945833,25.666667,254.875000
2,ACURA,NSX,3.500000,6.000000,11.100000,10.800000,11.000000,26.000000,261.000000
3,ACURA,RDX,2.535714,4.714286,11.607143,8.878571,10.371429,27.071429,242.250000
4,ACURA,RLX,3.500000,6.000000,11.900000,7.700000,10.000000,28.000000,231.666667
...,...,...,...,...,...,...,...,...,...
404,VOLVO,V90,2.000000,4.000000,10.600000,7.550000,9.233333,30.500000,215.500000
405,VOLVO,XC40,2.000000,4.000000,10.350000,7.550000,9.100000,30.750000,212.500000
406,VOLVO,XC60,2.537037,4.962963,12.070370,8.818519,10.607407,27.000000,245.111111
407,VOLVO,XC70,2.760000,5.400000,12.480000,9.070000,10.940000,26.200000,252.200000
408,VOLVO,XC90,2.300000,4.500000,12.065000,9.305000,10.845000,26.250000,251.700000